---
title: "TestPie"
author: "Grant Nickles"
date: "12/6/2019"
output: html_document
---
```{r}
library(phyloseq)
library(ggplot2)
library(vegan)
library(plyr)
library(psadd)

```

```{r}
seed <- readRDS("seeds.RDS")
peel <- readRDS("peel.RDS")
calyx <- readRDS("calyx_end.RDS")
pulp <- readRDS("fruit_pulp.RDS")
```

```{r}
seed2 <- readRDS("seeds2.RDS")
peel2 <- readRDS("peel2.RDS")
calyx2 <- readRDS("calyx_end2.RDS")
pulp2 <- readRDS("fruit_pulp2.RDS")
```

```{r}
apple <- merge_phyloseq(seed, peel, calyx, pulp)
dfTest = psmelt(apple)
dfTest = subset(dfTest, Abundance != 0, select = c("Abundance", "OTU", "Sample", "tissue", "mngmt", "Kingdom", "Phylum"))
#apple2 <- merge_phyloseq(seed2, peel2, calyx2, pulp2)
```

```{r}
apple = subset_taxa(apple, Genus != "-1")
```

```{r}
#ordinate

apple_pcoa <- ordinate(
  physeq = apple,
  method = "PCoA",
  distance = "co"  # the co is the best method for displaying the groupings
)
p <- plot_ordination(
  physeq = apple,
  ordination = apple_pcoa,
  color = "tissue",
  shape = "tissue",
  title = "PCoA of the bacterial communities in Apples"
)
plot(p)
```
```{r}
#ordinate

apple_pcoa <- ordinate(
  physeq = apple,
  method = "PCoA",
  distance = "co"  # the co is the best method for displaying the groupings
)
p <- plot_ordination(
  physeq = apple,
  ordination = apple_pcoa,
  color = "mngmt",
  shape = "mngmt",
  title = "PCoA of the bacterial communities in Apples"
)
plot(p)
```
```{r}
appleNOseed <- merge_phyloseq(peel, calyx, pulp)
```

```{r}
#ordinate

apple_pcoa <- ordinate(
  physeq = appleNOseed,
  method = "PCoA",
  distance = "co"  # the co is the best method for displaying the groupings
)
p <- plot_ordination(
  physeq = appleNOseed,
  ordination = apple_pcoa,
  color = "mngmt",
  shape = "mngmt",
  title = "PCoA of the bacterial communities in Apples"
)
plot(p)
```



```{r}
df = ldply(plist, function(x) x$data)
names(df)[1] <- "distance"
p = ggplot(df, aes(Axis.1, Axis.2, color=mngmt, shape=tissue))
p = p + geom_point(size=3, alpha=0.5)
p = p + facet_wrap(~distance, scales="free")
p = p + ggtitle("PCoA on various distance metrics for apple dataset")
p
```

